### ISSUE TITLE
How to install the drush command 'provision-site_make'

### ISSUE THREAD

**Issue by PascalAnimateur** [mglaman/hosting_site_make#1]
Should the drush/ directory content be placed undex ~/.drush/provision_site_make in order to enable the drush part of the module?

> The drush command 'provision-site_make' could not be found. Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions

**Comment by mglaman** [comment]
The whole repo can just be put under ~/. drush and it'll be discovered

**Comment by PascalAnimateur** [comment]
Thanks!!
